### PR TITLE
Bug: Remove first two logos #38

### LINKED ISSUE #38: Bug: Remove first two logos
We would need some change in the brand assets, you can access the page in [hack4bengal.tech/brand](https://www.hack4bengal.tech/brand), where we would remove the first two logos.

- Hack4Bengal Wide Govt. Infused Logo Light
- Hack4Bengal Wide Govt. Infused Logo Dark

image

### PR DESCRIPTION
**Pull request by jude-san**
closes #38 

## Tasks done:
- made changes to the file `BrandAssetsData.js`  in src\pages\brand\ 
- removed the first two logo imports from the  `BrandAssetsData.js`  file.
- renamed the images imports in  `BrandAssetsData.js`

## Screenshots
Screenshot (15)
Screenshot (13)

### CODE REVIEW

**Comment by tamalCodes** [comment]
Please write the issue you are closing in your PR description in `KEYWORD #ISSUE-NUMBER` for example `closes #issuenumber` without the backticks.

Also write the tasks done.

**Comment by jude-san** [comment]
> Please write the issue you are closing in your PR description in `KEYWORD #ISSUE-NUMBER` for example `closes #issuenumber` without the backticks.
> 
> Also write the tasks done.

Noted

**Comment by jude-san** [comment]
@tamalCodes added a description, please check it out.

**Comment by tamalCodes** [comment]
I edited the description a little bit, that is a good way to format it. Do take a look.

**Review by tamalCodes — APPROVED** [review]
LGTM.
Thankyou so much for contributing to Hack4Bengal.

**Comment by jude-san** [comment]
> I edited the description a little bit, that is a good way to format it. Do take a look.
Thanks.

**Pull request merged**
