### PR TITLE
delete: /team page removed including the route, Removed team navlink from the navbar and Meet our team section from homepage too

### PR DESCRIPTION
**Pull request by apneduniya**
image

Issue of https://github.com/hack4bengal/s3/issues/14

### CODE REVIEW

**Comment by tamalCodes** [comment]
Hi @apneduniya , please never raise PRs without the maintainer's/owner's consent. OSS is not a competition to get the PRs merged, take it slow. Respect the space, and collaborate.

Closing this pr for now.

**Comment by apneduniya** [comment]
It was not assigned when I was doing my work otherwise I would not, but yeah sorry for the issue then

**Comment by tamalCodes** [comment]
> It was not assigned when I was doing my work otherwise I would not, but yeah sorry for the issue then

Even if it is not assigned, never start to work.

**Comment by apneduniya** [comment]
> > It was not assigned when I was doing my work otherwise I would not, but yeah sorry for the issue then
> 
> Even if it is not assigned, never start to work.

Got it will remember

**Pull request closed without merging**
