### PR TITLE
fix: changes made to judge section and replaced with mentors keyword

### PR DESCRIPTION
**Pull request by taran1326**
edited the URI. 
initial -> localhost:3000/#judges , now -> localhost:3000/#mentors.
Screenshot 2023-10-24 at 13 22 43

### CODE REVIEW

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Great work can you also edit the data so that this card is removed from the mentors section ?

image

**Comment by taran1326** [comment]
> Great work can you also edit the data so that this card is removed from the mentors section ?
> 
> image

Sure I can do that!

**Comment by taran1326** [comment]
Hey  @tamalCodes  I was facing issues while implementing changes on this branch so I made a completely new branch (changebranch) and made all the changes , please review it and merge the pr. 
(Can you please suggest some guide to study how to incorporate requested changes and again create a pull request.)
Thank You !

**Comment by tamalCodes** [comment]
Hi @taran1326 , you don't need to make a new PR if you have a PR made already. Just change the branch locally to main, and update it. Also update your branch with respect to the main branch.

Once done just make the changes and commit, it will automatically be added to PR (if you already have one).

In this case, since you made that PR, I will be closing this one. But keep this in mind.

**Pull request closed without merging**
