### PR TITLE
Improved the Navbar Logo

### PR DESCRIPTION
**Pull request by Shinjan-saha**
The Logo's Width was to small in Navbar So I improved it by decreasing the  padding in navbar 

https://s3-shinjan-hack4bengal-test.vercel.app/

here I Deployed the Website in Vercel  of my own Cloned Repo with the changes i have done , So please See to it 

Thanking you in Anticipation

### CODE REVIEW

**Comment by Shinjan-saha** [comment]
please merge this Pull Request

**Comment by imanishbarnwal** [comment]
It seems better earlier, can you find some other issues to fix? I will also create some issues here in this repo soon. Thank You!!

**Comment by Shinjan-saha** [comment]
> It seems better earlier, can you find some other issues to fix? I will also create some issues here in this repo soon. Thank You!!

Will Sure Try

**Comment by Shinjan-saha** [comment]
#2 Removed the West Bengal Government Logo & added the  Hack 4 Bengal  White Transparent Logo

**Comment by Shinjan-saha** [comment]
#5 Added the Pre-Registration button with the Form Link  by modifying the "Application Closed " button

**Comment by Shinjan-saha** [comment]
@imanishbarnwal I have Undid the changes in Navbar Logo Size as I Have taken your suggestion & kept the previous one only   & Solved the Issue #2  & #5 
So can you please merge my Pull Request It have passed all the Safety checks also 
Thank you

**Comment by imanishbarnwal** [comment]
Thanks, @Shinjan-saha but please work on one issue at a time.... #5 is fixed by someone else. You can work on #2 can you propose a different design because the current one with a simple logo is not looking good. Let me know what you think about this, thank you!!

**Pull request closed without merging**
