### PR TITLE
moved timeline before venue in navbar

### PR DESCRIPTION
**Pull request by Sharjeel-Afridi**
as timeline div is above venue then it should also be before venue in navbar.
(accept pr in hacktoberfest)

### CODE REVIEW

**Comment by Sharjeel-Afridi** [comment]
Screenshot 2023-10-23 at 11 12 07 AM

here is a screenshot for reference
Screenshot 2023-10-23 at 11 13 22 AM

**Comment by imanishbarnwal** [comment]
Hi @Sharjeel-Afridi thanks, can you please comment out the venue section from the Nav bar and website? We don't need that part for now.

**Comment by tamalCodes** [comment]
@Sharjeel-Afridi Please mention the issue that was assigned to you in this format:  closes #(issuenumber here like #11)

**Comment by Sharjeel-Afridi** [comment]
> Hi @Sharjeel-Afridi thanks, can you please comment out the venue section from the Nav bar and website? We don't need that part for now.

yes, should i close this PR and make another PR with the venue section commented out?

**Comment by Sharjeel-Afridi** [comment]
> @Sharjeel-Afridi Please mention the issue that was assigned to you in this format: closes #(issuenumber here like #11)

actually, i did not raise an issue and neither was i assigned any issue. I just made the changes and opened a PR.

**Comment by imanishbarnwal** [comment]
Please comment out these sections as well

image

**Comment by imanishbarnwal** [comment]
I guess you missed the live button on nav bar to comment... also do pull before pushing hero section has been changed a bit

**Comment by imanishbarnwal** [comment]
Great work bro!!

**Pull request merged**
