### PR TITLE
fix: changes to testimonial linkedin ids

### PR DESCRIPTION
**Pull request by rajdeepbuilds**
Updated all Testimonials LinkedIn including 
1.Riddhi Dutta
2.Debashis Sen
3.Arsh Goyal
4.Soumyadip Chowdhury

5.For Prof. (Dr.) Dhrubajyoti Chattopadhyay , can't find his LinkedIn, so i put his google scholar ID 
   "https://scholar.google.co.in/citations?user=rVa_c-UAAAAJ&hl=en"

   Hope that will work.

### CODE REVIEW

**Review by tamalCodes — APPROVED** [review]
Great work !

**Comment by rajdeepbuilds** [comment]
Thank You @tamalCodes

**Comment by tamalCodes** [comment]
Hi @rajdeepbuilds , please fix the conflicts

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Please fix the conflicts

**Comment by rajdeepbuilds** [comment]
kindly check @tamalCodes

**Review by tamalCodes — APPROVED** [review]
LGTM 🎉

Thankyou for contributing to Hack4Bengal. Also, do not commit `package-lock.json` file until and unless you are actually making any changes to the dependencies.

**Comment by rajdeepbuilds** [comment]
Okay got it @tamalCodes da 
Thank you for the guidance 😊

**Pull request merged**
