### PR TITLE
[FIX]: Improved Accessibility to 100%

### LINKED ISSUE #48: Bug: Improving acessibility of the website
### Description

Currently, as you can see the accessibility score is pretty low, the issue is to make this score as high as possible.

- Some image elements do not have an alt tag
- Some image elements have alt tags but the description is very much different than what it should be
- The Links do not have a discernible name

### Proposed Solution

- You can generate the alt tags using [alt-text generator](https://alttext.in/)
- You can add `aria-label` or research more about how to make links accessible

### Screenshots

image

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/hack4bengal/s3/issues)
- [ ] I am willing to work on this issue (blank for no).

### PR DESCRIPTION
**Pull request by harith-hacky03**
closes #48

### CODE REVIEW

**Comment by harith-hacky03** [comment]
@tamalCodes Thanks for your guidance i finally made it to 100% in both mobile and the desktop . Its nice to have a guidance from person like you. Can i get any of your social media connection like linkedin to take guidance if i needed. Here is the link check it out https://s3-website-cprngnlkx-h4b-2.vercel.app/ . Thank you .

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Wow, amazing contribution howver: 

There's a missing image error in the Footer of the current site which is fixed in the [main site](https://www.hack4bengal.tech/)

image



Also I realised that the colour of the background heading has been altered a little bit to match the contrasts in the accessibility is it possible that we reduce the opacity or make it much more similar to what we have currently ?


image

**Comment by harith-hacky03** [comment]
@tamalCodes I changed the color very minimal so that the accessibility stays 100% .So changing color is little bit difficult the accessibility will be lowered. I will change the bg image and I will submit my PR.Thank you. I am ready take the seo to 100% too if you assign me by any chance .

**Comment by harith-hacky03** [comment]
@tamalCodes Everything is fixed you can merge it now. Thank you.

**Review by tamalCodes — APPROVED** [review]
Amazing work !

**Comment by harith-hacky03** [comment]
@tamalCodes Can you assign me the performance or seo improvement ? Thank you.

**Pull request merged**
